#!/bin/bash
source /usr/share/yunohost/helpers
source _common.sh

app=$YNH_APP_INSTANCE_NAME

nexora_validate_yunohost_version

ynh_script_progression --message="Stopping service before restore validation..." --weight=1
systemctl stop "$app" || true

nexora_setup_operator_role_lock

ynh_script_progression --message="Restoring sources..." --weight=3
ynh_restore_file --origin_path="$install_dir"
ynh_restore_file --origin_path="$data_dir"

ynh_script_progression --message="Restoring systemd service..." --weight=1
ynh_restore_file --origin_path="/etc/systemd/system/$app.service"
systemctl daemon-reload
systemctl enable "$app"

ynh_script_progression --message="Starting service..." --weight=1
systemctl start "$app"

ynh_script_progression --message="Restore complete." --last
