#!/bin/bash
source /usr/share/yunohost/helpers
source _common.sh

nexora_validate_yunohost_version restore

ynh_script_progression --message="Stopping service before restore validation..." --weight=1
systemctl stop "$app" || true

nexora_setup_operator_role_lock

ynh_script_progression --message="Restoring sources..." --weight=3
ynh_restore_file --origin_path="$install_dir"
ynh_restore_file --origin_path="$data_dir"

ynh_script_progression --message="Restoring NGINX configuration..." --weight=1
ynh_restore_file --origin_path="/etc/nginx/conf.d/$domain.d/$app.conf"
ynh_config_add_nginx

ynh_script_progression --message="Restoring systemd service..." --weight=1
ynh_restore_file --origin_path="/etc/systemd/system/$app.service"
systemctl daemon-reload
systemctl enable "$app"

ynh_script_progression --message="Restoring log rotation..." --weight=1
mkdir -p "/var/log/$app"
ynh_config_add_logrotate

ynh_script_progression --message="Integrating service in YunoHost..." --weight=1
yunohost service add "$app" --description="Nexora Control Plane" --log="/var/log/$app/$app.log"

ynh_script_progression --message="Starting service..." --weight=1
ynh_systemctl --service="$app" --action="start" --log_path="/var/log/$app/$app.log"

ynh_script_progression --message="Restore complete." --last
