#!/bin/bash
source /usr/share/yunohost/helpers
source _common.sh

app=$YNH_APP_INSTANCE_NAME

nexora_validate_yunohost_version

ynh_script_progression --message="Stopping service before upgrade..." --weight=1
systemctl stop "$app" || true

nexora_abort_if_port_busy

ynh_script_progression --message="Extracting sources..." --weight=3
ynh_setup_source --dest_dir="$install_dir/repo"

ynh_script_progression --message="Updating Python virtualenv..." --weight=5
nexora_setup_venv "$install_dir/venv" "$install_dir/repo"

nexora_setup_operator_role_lock

ynh_script_progression --message="Updating systemd service..." --weight=1
ynh_add_systemd_config

ynh_script_progression --message="Starting service..." --weight=1
systemctl start "$app"

ynh_script_progression --message="Upgrade complete." --last
